config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pools do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :destroy]
  resources :reviews, except: [:new, :create]
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  patch '/bookings/:id', to: 'bookings#change_status', as: :booking_status_change
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_date.rb
class AvailableDate < ApplicationRecord
  belongs_to :pool
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pool
  belongs_to :user
  validates :start_date, :end_date, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :pools
end

app/models/pool.rb
class Pool < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
  has_many :reviews
  has_many :available_dates
  has_many :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true, length: {minimum: 20}
  validates :photos, presence: true, length: {minimum: 2}

  include PgSearch::Model
  pg_search_scope :search_by_location,
    against: [:location],
    using: {
      tsearch: { prefix: true }
  }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :pool
  validates :description, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews
  has_many :pools
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def create
    if !current_user
      redirect_to new_user_session_path
    else
      @booking = Booking.new(booking_params)
      @booking.pool_id = params[:pool_id]
      @booking.user_id = current_user.id
      if @booking.save
        redirect_to dashboard_path, notice: "You have booked your pool!"
      else
        @pool = Pool.find(params[:pool_id])
        @markers = [
        {
            lat: @pool.latitude,
            lng: @pool.longitude,
            infoWindow: render_to_string(partial: "info_window", locals: { pool: @pool }),
            image_url: helpers.asset_url('geo_pool.png')
          }
        ]
       @booking = Booking.new
        render "pools/show"
      end
    end
  end

  def change_status
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.save
    redirect_to dashboard_path(current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to dashboard_path(current_user)
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @pools = Pool.all
    @pools_sample = @pools.sample(9)
  end

  def dashboard
    @my_bookings = current_user.bookings
    @my_pools = current_user.pools

    @my_booking_requests = Booking.all.select do |booking|
    booking.pool.user == current_user
    end
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only:[:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @pools = Pool.where("city ILIKE ?", "%#{params[:query]}%")
      @pools.geocoded
    else
      @pools = Pool.all.geocoded
    end
 # returns flats with coordinates
    @markers = @pools.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude
      }
    end
  end

  def show
    @markers = [
      {
        lat: @pool.latitude,
        lng: @pool.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pool: @pool }),
        image_url: helpers.asset_url('geo_pool.png')
      }
    ]
     @booking = Booking.new
     @reviews = @pool.reviews
     @review = Review.new
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
    if @pool.save
      redirect_to pool_path(@pool), notice: "Creating your pool"
    else
      render :new
    end
  end

  private

  def set_pool
    @pool = Pool.find(params[:id])
  end

  def pool_params
    params.require(:pool).permit(:name, :location, :city, :description, :capacity, :price, :has_lifeguard, :children_friendly, :jacuzzi_section, :climatization, :pool_side, :has_floats, :towels_include, :pet_friendly, :salted_water, :includes_bar, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    if !current_user
      redirect_to new_user_session_path
    else
      @review = Review.new(review_params)
      @review.user_id = current_user.id
      @review.pool_id = params["pool_id"]
      @pool = @review.pool
      if @review.save
        redirect_to pool_path(@pool, anchor: "submit-review-button")
      end
    end
  end

  private

  def review_params
     params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="main-container">
  <h2>
    Here is your booking
  </h2>
  <p> <strong>Pool</strong>
  <%= @booking.pool.name %>
   </p>

   <p> <strong>Status</strong>
    <%= @booking.status %></p>
</div>

<%= link_to "All bookings", dashboard_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

     <!-- <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p> -->
  </head>

  <body>


    <%= render 'shared/navbar_logged' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="main-container">
   <div class="dashboard-container">

  <h1> <strong> Dashboard </strong></h1>


<!--  Your listed pools -->
<h2> Your listed pools </h2>
  <div class='cards'>
    <% @my_pools.each do |pool| %>
    <a class = "link-card" href="/pools/<%=pool.id%>">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path pool.photos.first.key %>)">
      <div class="card-trip-description">
        <h3 style="font-size:30px"><%= pool.name %></h3>
      </div>
    </div>
    </a>
    <% end %>
  </div>

<!--   <div class="card-dashboard">
    <div class='row justify-content'>
    <h2> Your listed pools </h2>
      <#% @my_pools.each do |pool|  %>
      <div class="card-trip-2 black-letters mb-3">
        <div class='card-trip-image' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<#%= cl_image_path pool.photos.first.key %>')">
        </div>
          <div class="card-trip-infos-2">
            <div>
              <div class="d-flex justify-content">
                  <h5><#%=pool.name%></h5>
              </div>
            </div>
            </div>
        </div>
      <#% end %>
      </div>
    </div>
  </div> -->

<br>

 <div class="card-dashboard">
     <h2> Pools you will visit </h2>
     <div class="row card-booking mb-2 mt-2">
        <div class="col">
          <h5>Pool name</h5>
        </div>
        <div class="col">
          <h5>Start Date</h5>
        </div>
        <div class="col">
          <h5>End Date</h5>
        </div>
        <div class="col">
          <h5>Current Status</h5>
        </div>
        <div class="col">
          <h5>Action</h5>
        </div>
     </div>
    <% @my_bookings.each do |booking| %>
    <div class="row card-booking mb-2 mt-2">
      <div class="col">
          <%= booking.pool.name %>
        </div>
        <div class="col">
          <%= booking.start_date.strftime"%A, %b %d"%>
        </div>
        <div class="col">
          <%= booking.end_date.strftime"%A, %b %d"%>
        </div>
        <div class="col">
          <%= booking.status.capitalize %>
          </div>
        <div class="col">
          <div class = 'd-flex justify-content-start-between'>
          <div ><%= link_to 'Show', booking_path(booking),  method: :show, class: "btn button-show"  %></div>
          <br>
          <div class = "ml-1"> <%= link_to 'Cancel', booking_path(booking), method: :delete, class: "btn button-delete"  %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <br>

 <div class="card-dashboard">
  <% if @my_booking_requests != [] %>
    <h2> Your booking requests </h2>
     <div class="row card-booking mb-2 mt-2">
        <div class="col">
          <h5>Pool name</h5>
        </div>
        <div class="col">
          <h5>User name</h5>
        </div>
        <div class="col">
          <h5>Start Date</h5>
        </div>
        <div class="col">
          <h5>End Date</h5>
        </div>
        <div class="col">
          <h5>Status</h5>
        </div>
     </div>
    <% @my_booking_requests.sort.each do |request| %>
    <div class="row card-booking mb-2 mt-2">
      <div class="col">
        <%= request.pool.name %>
      </div>
      <div class="col">
        <%= request.user.name %>
      </div>
      <div class="col">
        <%= request.start_date.strftime"%A, %b %d"%>
      </div>
        <div class="col">
        <%= request.end_date.strftime"%A, %b %d"%>
      </div>
      <div class="col">
        <% if request.status == "pending" %>
        <div class = 'd-flex justify-content-start-between'>
          <div ><%= link_to "Accept", booking_status_change_path(request, status: "accepted"), method: :patch, class: "btn button-accept" %></div>
          <br>
          <div class = "ml-1"><%= link_to "Reject", booking_status_change_path(request, status: "rejected"), method: :patch, class: "btn button-reject" %></div>
          </div>
        <% elsif request.status == "accepted" %>
          <p style = "color: #1b6ca8; font-weight: bold"><%= request.status.capitalize %> </p>
        <% else %>
          <p style = "color: #e7305b; font-weight: bold"><%= request.status.capitalize %> </p>
        <% end %>
      </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>

app/views/pages/home.html.erb
<!-- COMPLETE FORM AT TOP OF PAGE TO LOOK FOR POOLS -->
<body>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('pool_banner.jpg')%>)">
<div class="main-container">
    <h1> Rent a pool <strong> and take a dip</strong></h1>
    <p> Have a mini vacation and relax </p>
    <div style="width:50%">
    <form accept-charset="UTF-8" action="/pools" method="get" >
      <div class="row in-line-search">
        <div class="col search-input">
          <input type="text" name = "query" class="form-control" placeholder="What city would you like to dive into?">
        </div>
       <button type="submit" class="red-button">Discover</button>
      </div>
    </form>
    </div>
</div>
</div>



<div class='main-container'>
<br><br>
<h2>Our best deals</h2>
<br><br>
<div class='cards'>
  <% @pools_sample.each do |pool| %>
  <a class = "link-card" href="/pools/<%=pool.id%>">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path pool.photos.first.key %>)">
    <div class = "card-trip-user">
      <p class="mt-2"><%= pool.user.name.capitalize %></p>
      <img src="<%= cl_image_path pool.user.avatar.key %>" class="avatar-bordered" />
    </div>
    <div class="card-trip-description">
      <h5 style="font-size:30px"><%= pool.name %></h5>
    </div>
    <div class= "d-flex justify-content">
      <p class= "card-trip-pricing mb-2 mr-2"><%=pool.price%>€</p>
      <p class="card-trip-pricing mb-2 ml-2"><%= pool.city.capitalize%></p>
    </div>
  </div>
  </a>
  <% end %>
  </div>
</div>
</body>

app/views/pools/_info_window.html.erb
<h2><%= pool.name %></h2>
<p><%= pool.location %></p>

app/views/pools/index.html.erb
<div class="main-container"; style= "margin-bottom: 10px">
  <div class="container-small"><h5>Search by city</h5></div>
  <!-- #location search bar -->
  <div class="container-small">
    <form accept-charset="UTF-8" action="/pools" method="get" >
      <div class="row in-line-search">
        <div class="col search-input">
          <input type="text" name="query" class="form-control" placeholder="Location">
        </div>
      <button type="submit" class="red-button">Search</button>
      </div>
    </form>
    </div>

  <div class="align-map mb-4">
    <div id="map"
        style="width: 800px; height: 400px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <!-- cars to show all  pools -->
<div class= "container">

  <div class='row'>
    <% @pools.each do |pool| %>
      <div class='col-md-6 col-lg-4 col-sm-6 black-letters'>
        <%= link_to pool_path(pool) do %>
          <div class="card-trip-2 black-letters mb-3">
            <div class='card-trip-image' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pool.photos.first.key %>')">
            </div>
              <div class="card-trip-infos-2">
                <div>
                  <div class="d-flex">
                      <h5><%=pool.name%></h5>
                  </div>
                  <div class="d-flex justify-content">
                    <i class="fas fa-city"></i>
                    <p class="mt-2 ml-2"><%= pool.city.capitalize%></p>
                    <i class="fas fa-swimmer ml-2"></i>
                    <p class="mt-2 ml-2"><%= pool.capacity%></p>
                  </div>
                </div>
                    <div class= "d-flex justify-content">
                      <img src="<%= cl_image_path pool.user.avatar.key %>" class="card-trip-user-2 avatar-bordered"/>
                      <h5 class= "card-trip-pricing"><%=pool.price%>€</h5>
                    </div>
                </div>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/pools/new.html.erb
<div class="container mt-5">

  <h2 class= "ml-5">Submit your pool</h2>
  <div class="main-container mt-4">
    <div class= 'row'>
      <div class="col-6 form-pool">

        <%= simple_form_for(@pool) do |f| %>

          <%= f.input :name %>
          <%= f.input :description%>
          <%= f.input :location, input_html: { class: "algolia-input" }%>
          <%= f.input :city%>
          <%= f.input :capacity, as: :numeric%>
          <%= f.input :price, as: :numeric%>
          <%= f.input :photos, as: :file, input_html: { multiple: true }%>
          <div class= "checkbox mt-3">
            <%= f.input :has_lifeguard%>
            <%= f.input :children_friendly%>
            <%= f.input :jacuzzi_section%>
            <%= f.input :climatization%>
            <%= f.input :pool_side%>
            <%= f.input :has_floats%>
            <%= f.input :towels_include%>
            <%= f.input :pet_friendly%>
            <%= f.input :salted_water%>
            <%= f.input :includes_bar%>
          </div>
        <%= f.submit class: 'btn btn-primary btn-lg btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pools/show.html.erb
<div class="main-container container-show">
  <div class="first-section row">
    <div class="border-show-card-up">
    </div>
    <div class="left-part">
      <div class="carousel-style">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @pool.photos.each_with_index do |photo, index| %>
            <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class="<%= "active" if index == 0 %>"></li>
            <% end  %>
          </ol>
          <div class="carousel-inner carousel-border carousel-style">
          <% @pool.photos.each_with_index do |photo, index| %>

                <div class="carousel-item carousel-style <%= "active" if index == 0 %>">
              <img class="d-block w-100 carousel-style" src=<%=photo.service_url %> alt="First slide">
            </div>
        <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
    </div>
    </div>
    </div>
    <div class="right-part">
      <div class="show-card">
        <div class="align-pool-name">
          <h2><%= @pool.name %></h2>
        </div>
        <div class="avatar-name">
          <img src="<%= cl_image_path @pool.user.avatar.key %>" class="avatar-large"/>
          <p> <%=@pool.user.name.capitalize  %></p>
        </div>
      </div>
        <br><br><br><br>
        <p><%= @pool.description %></p>
        <div class="align-price"><p><%= @pool.price %> ‎€</p></div>
    </div>

  </div>
  <div class="border-show-card-down"></div>
  <br><br><br><br>
  <div class="row align-features">
    <% if @pool.has_lifeguard? == true %>
      <p class="col-3 mt-4">Has lifeguard  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.children_friendly? == true %>
      <p class="col-3 mt-4">Children friendly  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.jacuzzi_section? == true %>
      <p class="col-3 mt-4">Jacuzzi_section <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.climatization? == true %>
      <p class="col-3 mt-4">Climatization  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.pool_side? == true %>
      <p class="col-3 mt-4">Pool slide  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.has_floats? == true %>
      <p class="col-3 mt-4">Has floats  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
      <% if @pool.towels_include? == true %>
      <p class="col-3 mt-4">Towels included  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
      <% if @pool.pet_friendly? == true %>
      <p class="col-3 mt-4">Pet friendly  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.salted_water? == true %>
      <p class="col-3 mt-4">Salted water  <i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
    <% if @pool.includes_bar? == true %>
      <p class="col-3 mt-4">Includes bar<i class="fa fa-check green" aria-hidden="true"></i></p>
    <% end %>
  </div>






  <div class="separate">
  </div>

  <div class="second-section row">
    <div class="show-ubication w-60">
      <br><br>
      <div>
          <div id="map"
            style="width: 100%; height: 400px"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
      </div>
    </div>

    <div class="show-ubication w-40">
<div class="container">
  <div class="container-show-form p-5">
    <div class="form-wrapper text-center">
      <h3>Book your pool</h3>
      <br>
      <%= simple_form_for [@pool, @booking] do |f| %>
        <div class="d-flex justify-content-center">
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker form-design form-left"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker form-design form-right"} %>
        </div>
        <%= f.button :submit, "Create booking", class: "red-button align-button w-100" %>
      <% end %>
    </div>
  </div>
</div>



  </div>




<br><br><br><br>
</div> 

<!-- REVIEWS -->
<div class="separate">
</div> 

<br>

<h3><%= pluralize @pool.reviews.count, "review" %></h3>

<% @reviews.each do |review| %>
<div class="card">
  <div class="card-body">
    <div class = "card-trip-user-align">
      <img src="<%= cl_image_path review.user.avatar.key %>" class="avatar-bordered" />
      <p class="mt-2 ml-2"><%= review.user.name.capitalize %></p>
    </div>
    <%= review.created_at.strftime"%A, %b %d" %>
    <ul class="card-trip-user-align pl-0">
    <%review.rating.times do%>
    <li style="list-style-type: none"><i style="color: #e7305b" class="fas fa-star"></i></li>
    <% end %>
    </ul>
    <p><%= review.description %></p>
  </div>
</div>
<br>
<% end %>

<h3 class="mt-3">Add your review!</h3>

<%= simple_form_for ([@pool, @review]) do |f| %>
  <%= f.input :description, as: :text %>
  <%= f.input :rating, as: :integer, input_html: { max: 5 }%>
  <div class = "red-button" id="submit-review-button"><%= f.button :submit%></div>
<% end %>

</div>

 
</div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the Four Muses
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <i class="fas fa-swimming-pool"></i>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="red-button" href="/users/sign_in">Log in</a>
        </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar_logged.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand logo-inline" href="/">
        <i class="fas fa-swimming-pool"></i>
            <div class="align-airpool"><h6>Air Pool</h6></div>
      </a>
<!--       <h5 class="logo">AirPool</h5> -->
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_user %>
          <li class="nav-item">
              <a class="nav-link navbar-btn" href="/pools/new">Add your pool</a>
            </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle mv-right" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.avatar.key %>" />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/dashboard">My dashboard</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
            </div>
          </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link navbar-btn" href="/users/sign_in">Sign in</a>
            </li>
          <% end %>
      </ul>
    </div>
</div>